name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # Mengizinkan jalannya automasi secara manual dari tab Actions GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://root:$HF_TOKEN@huggingface.co/spaces/cakrabudiman/fastapi-cloud-demo
          git push --force hf main
