name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Menggunakan alat resmi HF untuk mengunggah folder proyek langsung ke Space
          huggingface-cli upload cakrabudiman/fastapi-cloud-demo . . --repo-type=space --token=$HF_TOKEN
