name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face Hub CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Jalankan perintah upload langsung via modul python agar aman dari error command not found
          python -m huggingface_hub.cli.cli_utils upload cakrabudiman/fastapi-cloud-demo . . --repo-type=space --token=$HF_TOKEN
